module.exports = {
  "plugins": [
      "stylelint-scss"
    ],
  "rules": {
    "scss/dollar-variable-colon-newline-after": "always-multi-line",
    "color-hex-case": "lower",
    "color-named": "never",
    "function-calc-no-unspaced-operator": true,
    "function-name-case": "lower",
    "number-no-trailing-zeros": true,
    "string-no-newline": true,
    "length-zero-no-unit": true,
    "unit-case": "lower",
    "unit-no-unknown": true,
    "value-keyword-case": "lower",
    "shorthand-property-no-redundant-values": true,
    "property-case": "lower",
    "property-no-unknown": true,
    "declaration-block-no-duplicate-properties": [ true, {
      ignore: ["consecutive-duplicates-with-different-values"],
    } ],
    "declaration-block-no-ignored-properties": true,
    "declaration-block-no-redundant-longhand-properties": true,
    // "declaration-block-no-shorthand-property-overrides": true, // ругается resetcss
    "declaration-block-single-line-max-declarations": 1,
    "declaration-block-trailing-semicolon": "always",
    "block-closing-brace-empty-line-before": "never",
    "block-no-empty": true,
    "block-opening-brace-newline-after": "always-multi-line",
    "selector-attribute-brackets-space-inside": "never",
    "selector-attribute-operator-space-after": "never",
    "selector-attribute-operator-space-before": "never",
    "selector-combinator-space-after": "always",
    "selector-combinator-space-before": "always",
    "selector-descendant-combinator-no-non-space": true,
    "selector-no-empty": true,
    "selector-pseudo-class-case": "lower",
    "selector-pseudo-class-no-unknown": true,
    "selector-pseudo-class-parentheses-space-inside": "never",
    "selector-pseudo-element-case": "lower",
    "selector-pseudo-element-no-unknown": true,
    "selector-type-case": "lower",
    "selector-type-no-unknown": true,
    "selector-max-empty-lines": 0,
    "media-feature-colon-space-after": "always",
    "media-feature-colon-space-before": "never",
    "media-feature-name-case": "lower",
    "media-feature-name-no-unknown": true,
    "media-feature-no-missing-punctuation": true,
    "media-feature-parentheses-space-inside": "never",
    "media-feature-range-operator-space-after": "always",
    "media-feature-range-operator-space-before": "always",
    "at-rule-name-case": "lower",
    "at-rule-semicolon-newline-after": "always",
    "indentation": 2,
    "no-empty-source": true,
    "no-extra-semicolons": true,
    "no-invalid-double-slash-comments": true,
    'no-unknown-animations': true,
  }
};